name: Convert Keystore

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Convert to base64
        run: base64 release.keystore > keystore_base64.txt
      - name: Upload base64
        uses: actions/upload-artifact@v4
        with:
          name: keystore-base64
          path: keystore_base64.txt
